use strict;
use warnings;

my $filename = 'envfiles.py';
open(my $fh, '>', $filename) or die "Could not open file '$filename' $!";

print $fh "My first report generated by perl\n";
print $fh "just test for added strings on file\n";
print $fh "ls -d \$PWD\/**\/*\(.\)\n";
print $fh system('ls -d \$PWD\/**\/*\(.\)');

close $fh;
print "done\n";
